# Uncomment the next line to define a global platform for your project
platform :ios, ’12.0’

#source ‘https://github.com/VladanAndjelkovic/MyPrivateLibraryPodspec.git'



target 'MyPrivateLibrary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyPrivateLibrary
	pod ‘MyPrivateLibrary’, :git => “https://github.com/VladanAndjelkovic/MyPrivateLibrary"

end


